import { h } from 'preact';
import style from './style';

const Home = () => (
  <div class={style.home}>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt arcu non sodales neque. Lacus sed viverra tellus in hac. Tincidunt tortor aliquam nulla facilisi cras. Quis viverra nibh cras pulvinar mattis nunc sed blandit. In nulla posuere sollicitudin aliquam. Iaculis nunc sed augue lacus viverra vitae congue eu consequat. Duis ultricies lacus sed turpis. Sit amet facilisis magna etiam tempor orci eu lobortis elementum. Lectus sit amet est placerat in. Urna duis convallis convallis tellus id. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Nisl vel pretium lectus quam id. At tempor commodo ullamcorper a lacus. Ultrices tincidunt arcu non sodales neque sodales ut. Pharetra et ultrices neque ornare aenean euismod.
  </p><p>
  Sapien faucibus et molestie ac feugiat sed lectus. Rhoncus urna neque viverra justo nec ultrices dui sapien. Ultrices vitae auctor eu augue ut lectus arcu. Massa tempor nec feugiat nisl pretium. A scelerisque purus semper eget duis. Dui vivamus arcu felis bibendum ut. Vitae aliquet nec ullamcorper sit. Tellus in metus vulputate eu scelerisque felis imperdiet proin fermentum. Facilisis leo vel fringilla est ullamcorper eget. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Nunc aliquet bibendum enim facilisis gravida. Condimentum vitae sapien pellentesque habitant morbi. Sed euismod nisi porta lorem mollis. Amet dictum sit amet justo. In mollis nunc sed id semper risus in. Sit amet justo donec enim diam vulputate.
  </p><p>
  Morbi tincidunt ornare massa eget egestas purus viverra accumsan. In egestas erat imperdiet sed euismod nisi. Tincidunt ornare massa eget egestas purus viverra. Id neque aliquam vestibulum morbi blandit cursus risus at ultrices. Nisl condimentum id venenatis a. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Elementum nisi quis eleifend quam adipiscing. Nulla aliquet enim tortor at auctor urna nunc. Sed libero enim sed faucibus turpis in eu mi bibendum. Quam pellentesque nec nam aliquam sem et tortor. At imperdiet dui accumsan sit. At elementum eu facilisis sed odio morbi quis. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Sem et tortor consequat id porta nibh venenatis cras sed. Sapien faucibus et molestie ac feugiat sed lectus vestibulum mattis.
  </p><p>
  Tellus molestie nunc non blandit massa enim nec. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus. Blandit aliquam etiam erat velit scelerisque. Adipiscing at in tellus integer. Nibh tortor id aliquet lectus proin nibh. Enim sit amet venenatis urna. Eu nisl nunc mi ipsum. Lorem donec massa sapien faucibus et molestie ac. Consectetur a erat nam at lectus. Sed felis eget velit aliquet sagittis id.
  </p><p>
  Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Quisque egestas diam in arcu cursus euismod quis. Mauris pharetra et ultrices neque ornare. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Orci phasellus egestas tellus rutrum tellus. Tortor consequat id porta nibh venenatis cras sed felis. Bibendum arcu vitae elementum curabitur vitae nunc sed velit dignissim. Eget nulla facilisi etiam dignissim. Euismod elementum nisi quis eleifend. Aenean et tortor at risus viverra adipiscing at. Faucibus nisl tincidunt eget nullam non nisi est sit amet. Accumsan sit amet nulla facilisi morbi tempus. Vitae nunc sed velit dignissim sodales ut eu. Felis donec et odio pellentesque diam. Velit aliquet sagittis id consectetur purus ut faucibus. Congue eu consequat ac felis donec et odio pellentesque.</p>
  </div>
);

export default Home;
